version: '3'

vars:
  

tasks:
  
  stop-tir:
    cmds:
      - docker-compose stop tirconnector
    silent: true  
  
  build-tir:
    cmds:
      - docker-compose build tirconnector
    silent: true  

  tir:
    cmds:
      - task stop-tir
      - task build-tir
    silent: true  

  up:
    cmds:
      - docker-compose up -d
    silent: true  

  sql:
    cmds:
      - docker-compose -f docker-compose_sql.yml up -d
    silent: true  

  restart:
    cmds:
      - docker-compose down && docker-compose up -d
    silent: true    

  restart-sql:
    cmds:
      - docker-compose -f docker-compose_sql.yml down && docker-compose -f docker-compose_sql.yml up -d
    silent: true    

  logs-tir:
    cmds:
      - docker-compose logs -f tirconnector
