SELECT ANCODICE AS CODICE_CONTO, ANDESCRI AS DESCR_CONTO, ANCONSUP AS MASTRO_RAGGR, MCSEZBIL AS SEZIONE_BIL,
	CASE 
		WHEN ANTIPSOT = 'X' THEN 'GENERICO'
		WHEN ANTIPSOT = 'B' THEN 'BANCA'
		WHEN ANTIPSOT = 'I' THEN 'IVA'
		WHEN ANTIPSOT = 'M' THEN 'CESPITE'
		WHEN ANTIPSOT = 'A' THEN 'CONTR. ACQUISTI'
		WHEN ANTIPSOT = 'V' THEN 'CONTR. VENDITE'
		WHEN ANTIPSOT = 'T' THEN 'APERTURA/CHIUSURA'
		WHEN ANTIPSOT = 'R' THEN 'INVENTARIALE'
		END AS TIPO_CONTO
FROM BERNCONTI C 
LEFT OUTER JOIN BERNMASTRI M ON C.ANCONSUP = M.MCCODICE
WHERE ANTIPCON = 'G'
