SELECT ANCODICE AS COD_CLI, ANDESCRI AS RAG_SOC, ANINDIRI AS INDIRIZZO, AN___CAP AS CAP, 
ANLOCALI AS LOCALITA, ANPROVIN AS PROV, ANNAZION AS NAZIONE, ANPARIVA AS P_IVA,
ANCODFIS AS CF, ANPERFIS AS PERSONA_FISICA, ANCATCON AS CAT_CONTABILE FROM BERNCONTI
WHERE ANTIPCON = 'C'