SELECT M.MMSERIAL AS SERIALE_MOV, MMDATREG AS DATA_REG, MMNUMREG AS NUM_REG, MMTCAMAG AS CAUSALE, CMDESCRI AS DESC_MOV, MMCODMAG AS MAGAZZINO, MMCODART AS ARTICOLO, MMQTAMOV AS QTA
FROM BERNMVM_MAST M 
LEFT OUTER JOIN BERNMVM_DETT D ON M.MMSERIAL = D.MMSERIAL
LEFT OUTER JOIN BERNCAM_AGAZ C ON MMTCAMAG = C.CMCODICE
ORDER BY MMDATREG ASC