 SELECT IVSERIAL AS SERIALE_PN, PNDATDOC AS DATA_DOC, PNNUMDOC AS NUM_DOC, PNALFDOC AS SERIE_DOC, PNCODCLF AS CODICE_CLIFOR, ANDESCRI AS DESCR_CLIFOR,
IVCODIVA AS COD_IVA, IVTIPREG AS ACQ_VEN, IVNUMREG AS NUM_REGISTRO, IVIMPONI AS IMPONIBILE,
IVIMPIVA AS IVA
FROM BERNPNT_IVA I 
LEFT OUTER JOIN BERNPNT_MAST M ON I.IVSERIAL=M.PNSERIAL
LEFT OUTER JOIN BERNCONTI C ON M.PNCODCLF=C.ANCODICE
ORDER BY PNDATDOC ASC