SELECT M.PNSERIAL AS SERIALE_PN, PNCODCAU AS CAUSALE, PNDATREG AS DATA_REG, PNCODCON AS CONTO, ANDESCRI AS DESC_CONTO, 
PNIMPDAR AS DARE, PNIMPAVE AS AVERE
FROM BERNPNT_DETT D
LEFT OUTER JOIN BERNCONTI C ON D.PNCODCON = C.ANCODICE
LEFT OUTER JOIN BERNPNT_MAST M ON D.PNSERIAL = M.PNSERIAL
WHERE ANTIPSOT = 'B'
ORDER BY PNDATREG ASC