SELECT M.PNSERIAL AS SERIALE_PN, PNCODCAU AS CAUSALE, PNNUMRER AS NUM_REG, PNDATREG AS DATA_REG, PNCODCON AS CONTO,
ANDESCRI AS DESC_CONT, PNIMPDAR AS DARE, PNIMPAVE AS AVERE
FROM BERNPNT_MAST M
LEFT OUTER JOIN BERNPNT_DETT D ON M.PNSERIAL = D.PNSERIAL
LEFT OUTER JOIN BERNCONTI C ON D.PNCODCON = C.ANCODICE
WHERE PNTIPREG = 'N'
ORDER BY PNDATREG ASC