SELECT ARTIPART AS TIPO_PROD, ARCODART AS COD_PRODOTTO, ARDESART AS DESCRIZIONE, ARDESSUP AS DESC_SUPPL,
ARUNMIS1 AS UM, ARCODIVA AS COD_IVA, ARCATCON AS CAT_CONTABILE, ARGRUMER AS GRUPPO_MERC, ARCATOMO AS CAT_OMOGENEA, ARCODFAM AS FAMIGLIA, ARDTOBSO AS DATA_OBS
FROM GUIDBART_ICOL
