SELECT M.PNSERIAL AS SERIALE_PN, PNCODCAU AS CAUSALE, PNDATREG AS DATA_REG, PNCODCON AS CONTO, ANDESCRI AS DESC_CONTO, 
PNIMPDAR AS DARE, PNIMPAVE AS AVERE
FROM GUIDBPNT_DETT D
LEFT OUTER JOIN GUIDBCONTI C ON D.PNCODCON = C.ANCODICE
LEFT OUTER JOIN GUIDBPNT_MAST M ON D.PNSERIAL = M.PNSERIAL
WHERE ANTIPSOT = 'B'
ORDER BY PNDATREG ASC