SELECT S.LICODART AS ARTICOLO, LICODLIS AS COD_LISTINO, LIPREZZO AS PREZZO, LISCONT1 AS SCONTO1, LISCONT2 AS SCONTO2, LIDATATT AS DATA_ATT, LIDATDIS AS DATA_FINE 

FROM GUIDBLIS_SCAG S
LEFT OUTER JOIN GUIDBLIS_TINI L ON S.LICODART=L.LICODART AND S.LIROWNUM = L.CPROWNUM

ORDER BY S.LICODART ASC, LICODLIS ASC, LIDATATT DESC