SELECT M.PNSERIAL AS SERIALE_PN, PNTIPDOC AS TIPO_DOC, PNCODCAU AS CAUSALE, CCDESCRI AS DESCR_CAUSALE, PNNUMDOC AS NUM_DOC, PNALFDOC AS SERIE_DOC,
PNDATDOC AS DATA_DOC, PNTIPCON AS TIPO_CONTO, PNCODCON AS CONTO, ANDESCRI AS DESC_CONTO, PNIMPDAR AS DARE,
PNIMPAVE AS AVERE
FROM GUIDBPNT_MAST M
LEFT OUTER JOIN GUIDBPNT_DETT D ON M.PNSERIAL=D.PNSERIAL
LEFT OUTER JOIN GUIDBCONTI C ON M.PNCODCLF=C.ANCODICE
LEFT OUTER JOIN GUIDBCAU_CONT CC ON M.PNCODCAU=CC.CCCODICE
WHERE PNTIPREG IN ('V', 'A')
ORDER BY PNDATDOC ASC

