SELECT M.PNSERIAL AS SERIALE_PN, PNCODCAU AS CAUSALE, PNNUMRER AS NUM_REG, PNDATREG AS DATA_REG, PNCODCON AS CONTO,
ANDESCRI AS DESC_CONT, PNIMPDAR AS DARE, PNIMPAVE AS AVERE
FROM GUIDBPNT_MAST M
LEFT OUTER JOIN GUIDBPNT_DETT D ON M.PNSERIAL = D.PNSERIAL
LEFT OUTER JOIN GUIDBCONTI C ON D.PNCODCON = C.ANCODICE
WHERE PNTIPREG = 'N'
ORDER BY PNDATREG ASC