SELECT M.MVSERIAL AS SERIALE_DOC, MVDATDOC AS DATA_DOC, MVNUMDOC AS NUM_DOC, MVALFDOC AS SERIE_DOC, MVTIPDOC AS CAUSALE,
MVCODCON AS CLIENTE, ANDESCRI AS RAG_SOC, MVCODART AS ARTICOLO, MVDESART AS DESC_ARTICOLO,
MVDESSUP AS DESC_SUPPL, MVQTAMOV AS QTA, MVUNIMIS AS UM,
MVPREZZO AS PREZZO 

FROM GUIDBDOC_MAST M
LEFT OUTER JOIN GUIDBDOC_DETT D ON M.MVSERIAL = D.MVSERIAL
LEFT OUTER JOIN GUIDBCONTI C ON MVCODCON = C.ANCODICE
WHERE MVFLVEAC = 'A' AND MVCLADOC = 'DT'
ORDER BY MVDATDOC ASC