SELECT  INDATINV as DATA_INV, DINUMINV AS NUM_INV, INDESINV AS DESCR_INV, DICODICE AS ARTICOLO, DIQTAESI AS ESISTENZA FROM GUIDBINVEDETT D 
LEFT OUTER JOIN GUIDBINVENTAR M ON D.DINUMINV = M.INNUMINV AND D.DICODESE = M.INCODESE
WHERE INSTAINV <> 'P' AND MONTH(INDATINV) = '12' AND DAY(INDATINV)='31'
ORDER BY DICODESE ASC, DINUMINV ASC
